### ISSUE TITLE
use DSL to create treants for testing

### ISSUE THREAD

**Issue by kain88-de** [datreant/datreant.core#147]
To make it easier to create treants for testing and specify how some special folder structures should look to test edge cases I suggested use a DSL to define treants from text snippets. YAML is a good choice for this.  Below are examples how the DSL could look with an example.

``` yaml                                                            
  folder:                                                                   
    name: 'foo'                                                             
    content: [...]                                                          
  ---                                                                       
  file:                                                                     
    name: 'bar'                                                             
  ---                                                                       
  treant:                                                                   
    name: 'guz'                                                             
    tags: [blub, blab, ...]                                                 
    categories: {png: True, close: False}                                   
    content: [...]                                                          
    limbs: [...]                                                            
  ---                                                                       
  limb:                                                                     
    type: data                                                              
    # custom-for-limb                                                       
```                                                                   
                                                                            
Here is a complete example.
                                                                            
``` yaml                                                            
  - treant:                                                                 
      name: test                                                            
      tags: [top]                                                           
      content:                                                              
        - folder:                                                           
            name: sub-test                                                  
        - file:                                                             
            name: test-file                                                 
        - treant:                                                           
            name: sub-treant                                                
            tags: [sub]                                                     
```                                                                   

It should be rather straight forward to implement this later. But it will get rid off the one-catch all treant we currently use.
